## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Sun Jun 19 10:58:12 PM PDT 2011
##
vlib work
vlog  +acc  "sha-256-functions.v"
vlog  +acc  "sha256_transform.v"
vlog  +acc  "bitbang_transmitter.v"
vlog  +acc  "bitbang_receiver.v"
vlog  +acc  "serial.v"
vlog  +acc  "fpgaminer_top.v"
vlog  +acc  "miner_test.v"
vlog  +acc  "/hd/cad/xilinx/ise9.2i/verilog/src/glbl.v"
vsim -t 1ps   -L xilinxcorelib_ver -L unisims_ver -lib work miner_test_v glbl
do {miner_test_v.udo}
view structure
view signals
run 1000ns
